version: '3.9'
services:
  haproxy1:
    build: ./haproxy1
    links:
      - app01
      - app02
    ports:
      - "3000:80"
  haproxy2:
    build: ./haproxy2
    links:
      - app01
      - app02
    ports:
      - "3001:81"

  app01:
    build: ./ws-server
    depends_on:
      - redis
    expose:
      - 3000

  app02:
    build: ./ws-server
    depends_on:
      - redis
    expose:
      - 3000
  redis:
    image: redis
    container_name: redis
    hostname: redis
    expose:
      - 6379
